name: Build and Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 0.1.0)'
        required: true
        default: ''

jobs:
  build:
    name: Build on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            platform: darwin
            arch: x64
          - os: macos-latest
            target: aarch64-apple-darwin
            platform: darwin
            arch: arm64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            platform: linux
            arch: x64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            platform: linux
            arch: arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            platform: win32
            arch: x64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev pkg-config

      - name: Temporarily modify package.json for build
        run: |
          node -e "
            const fs = require('fs');
            const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
            delete pkg.os;
            delete pkg.cpu;
            fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          "

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          CARGO_TARGET_DIR: ${{ github.workspace }}/target

      - name: Prepare package
        run: |
          mkdir -p dist/${{ matrix.platform }}-${{ matrix.arch }}
          cp index.node dist/${{ matrix.platform }}-${{ matrix.arch }}/
          cp index.d.ts dist/
          cp package.json dist/
          cp README.md dist/
          cp -r examples dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.platform }}-${{ matrix.arch }}
          path: dist
          retention-days: 1

  publish:
    name: Publish to npm
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare package
        run: |
          mkdir -p dist
          cp index.js dist/
          cp index.d.ts dist/
          cp package.json dist/
          cp README.md dist/
          cp -r examples dist/
          mkdir -p dist/bin

          # Create platform-specific directories
          mkdir -p dist/bin/darwin-x64
          mkdir -p dist/bin/darwin-arm64
          mkdir -p dist/bin/linux-x64
          mkdir -p dist/bin/linux-arm64
          mkdir -p dist/bin/win32-x64

          # List artifacts for debugging
          find artifacts -type f -name "*.node" | sort

          # Copy the binaries from artifacts with better error handling
          if [ -f artifacts/binaries-darwin-x64/darwin-x64/index.node ]; then
            cp artifacts/binaries-darwin-x64/darwin-x64/index.node dist/bin/darwin-x64/
            echo "✅ macOS x64 binary copied successfully"
          else
            echo "⚠️ No macOS x64 binary found"
            ls -la artifacts/binaries-darwin-x64 || echo "Directory not found"
          fi

          if [ -f artifacts/binaries-darwin-arm64/darwin-arm64/index.node ]; then
            cp artifacts/binaries-darwin-arm64/darwin-arm64/index.node dist/bin/darwin-arm64/
            echo "✅ macOS ARM64 binary copied successfully"
          else
            echo "⚠️ No macOS ARM64 binary found"
            ls -la artifacts/binaries-darwin-arm64 || echo "Directory not found"
          fi

          if [ -f artifacts/binaries-linux-x64/linux-x64/index.node ]; then
            cp artifacts/binaries-linux-x64/linux-x64/index.node dist/bin/linux-x64/
            echo "✅ Linux x64 binary copied successfully"
          else
            echo "⚠️ No Linux x64 binary found"
            ls -la artifacts/binaries-linux-x64 || echo "Directory not found"
          fi

          if [ -f artifacts/binaries-linux-arm64/linux-arm64/index.node ]; then
            cp artifacts/binaries-linux-arm64/linux-arm64/index.node dist/bin/linux-arm64/
            echo "✅ Linux ARM64 binary copied successfully"
          else
            echo "⚠️ No Linux ARM64 binary found"
            ls -la artifacts/binaries-linux-arm64 || echo "Directory not found"
          fi

          if [ -f artifacts/binaries-win32-x64/win32-x64/index.node ]; then
            cp artifacts/binaries-win32-x64/win32-x64/index.node dist/bin/win32-x64/
            echo "✅ Windows x64 binary copied successfully"
          else
            echo "⚠️ No Windows x64 binary found"
            ls -la artifacts/binaries-win32-x64 || echo "Directory not found"
          fi

          # Verify all binaries were copied
          echo "Verifying binaries in dist/bin:"
          find dist/bin -type f | sort

      - name: Modify package.json for platform-specific binaries
        run: |
          node -e "
            const fs = require('fs');
            const pkg = JSON.parse(fs.readFileSync('dist/package.json', 'utf8'));
            pkg.main = 'index.js';
            delete pkg.gypfile;
            pkg.os = ['darwin', 'linux', 'win32'];
            pkg.cpu = ['x64', 'arm64'];
            fs.writeFileSync('dist/package.json', JSON.stringify(pkg, null, 2));
          "

      - name: Set version from workflow dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          cd dist
          npm version ${{ github.event.inputs.version }} --no-git-tag-version --allow-same-version
          echo "Publishing version ${{ github.event.inputs.version }}"

      - name: Set version from tag
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: |
          # Extract version from tag (remove the 'v' prefix)
          TAG=${GITHUB_REF#refs/tags/v}
          echo "Extracted version: $TAG"

          # Read current version from package.json
          CURRENT_VERSION=$(node -p "require('./dist/package.json').version")
          echo "Current version in package.json: $CURRENT_VERSION"

          # Set the version in the dist package.json
          cd dist
          npm version $TAG --no-git-tag-version --allow-same-version
          echo "Set version to $TAG in dist/package.json"

      - name: Publish to npm
        run: |
          cd dist
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
